"""add pwd field

Revision ID: 015499e234c1
Revises: 1225e1e7172b
Create Date: 2023-05-14 12:29:09.009914

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '015499e234c1'
down_revision = '1225e1e7172b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('hashed_pwd', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermodel', 'hashed_pwd')
    # ### end Alembic commands ###
