"""update date

Revision ID: 1225e1e7172b
Revises: efb673326e27
Create Date: 2023-01-26 16:13:15.661608

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1225e1e7172b'
down_revision = 'efb673326e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.alter_column('usermodel', 'name_user',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('usermodel', 'change_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('change_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('usermodel', 'name_user',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('usermodel', 'update_date')
    # ### end Alembic commands ###
