"""add role and district

Revision ID: 4f2014c21c7d
Revises: f19249efe3d2
Create Date: 2022-05-17 21:47:36.345019

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4f2014c21c7d'
down_revision = 'f19249efe3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citymodel', sa.Column('district', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('usermodel', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('usermodel', 'number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usermodel', 'number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('usermodel', 'role')
    op.drop_column('citymodel', 'district')
    # ### end Alembic commands ###
