"""change data structure

Revision ID: efb673326e27
Revises: 4f2014c21c7d
Create Date: 2023-01-22 20:05:51.048632

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'efb673326e27'
down_revision = '4f2014c21c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citymodel', 'postal_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('usermodel', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('usermodel', sa.Column('change_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermodel', 'change_date')
    op.drop_column('usermodel', 'create_date')
    op.alter_column('citymodel', 'postal_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
